### ISSUE TITLE
Cannot start worker in rapids 23.02

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/dask-cuda#1122]
With a rapids 23.02-based container , and confirming `dask_cuda` 23.02.00 and `click` 8.0.4, the following docker-compose dask cuda cli command throws a error:

```yml
    command: [
      "dask", "cuda", "worker", "dask-scheduler:8786"
    ]
```

=>

```
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486860023Z Traceback (most recent call last):
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486862637Z   File "/opt/conda/envs/rapids/bin/dask", line 10, in <module>
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486863138Z     sys.exit(main())
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486863529Z   File "/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/__main__.py", line 5, in main
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486864070Z     run_cli()
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486864411Z   File "/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/cli.py", line 79, in run_cli
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486864832Z     _register_command_ep(cli, ep)
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486865543Z   File "/opt/conda/envs/rapids/lib/python3.8/site-packages/dask/cli.py", line 56, in _register_command_ep
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486866495Z     command = entry_point.load()
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486866956Z   File "/opt/conda/envs/rapids/lib/python3.8/importlib/metadata.py", line 77, in load
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486867617Z     module = import_module(match.group('module'))
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486867977Z   File "/opt/conda/envs/rapids/lib/python3.8/importlib/__init__.py", line 127, in import_module
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486868498Z     return _bootstrap._gcd_import(name[level:], package, level)
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486869270Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486869911Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486870222Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486870492Z   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486870703Z   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486871023Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486872025Z   File "/opt/conda/envs/rapids/lib/python3.8/site-packages/dask_cuda/cli.py", line 61, in <module>
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486872396Z     @cuda.command(name="worker", context_settings=dict(ignore_unknown_options=True))
compose-dask-cuda-worker-1       | 2023-02-19T00:16:27.486872786Z AttributeError: 'function' object has no attribute 'command'
```

I saw:

https://github.com/rapidsai/dask-cuda/blame/e2db7c9112474a1de7dda9624c710721d1dcd3ca/dask_cuda/cli.py#L56

where maybe `@click.group` => `@click.group()` to match examples 
 https://click.palletsprojects.com/en/8.1.x/commands/ ?

**Comment by lmeyerov** [comment]
Digging: looks like we were using the latest `click` on conda (8.0.4), while `2023.02` works with latest from pypi (8.1.3), which rapids 23.02 base image correctly provides . Not sure why we have a downgraded one.
