### ISSUE TITLE
`dask cuda` CLI doesn't work with click 8.0.x

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/dask-cuda#1271]
I just ran into an issue with running `dask cuda worker` if you have `click 8.0.x`.

```console
$ conda create -n dask-cuda-click -y -c conda-forge python=3.10

$ conda activate dask-cuda-click

$ pip install dask[complete] dask-cuda==23.10.0 click==8.0.4

$ dask cuda worker
/home/jtomlinson/miniconda3/envs/dask-cuda-click/lib/python3.10/site-packages/dask/cli.py:100: UserWarning: While registering the command with name 'cuda', an exception ocurred; 'function' object has no attribute 'command'.
  warnings.warn(
Usage: dask [OPTIONS] COMMAND [ARGS]...
Try 'dask -h' for help.

Error: No such command 'cuda'.

$ python -c "import dask_cuda.cli"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jtomlinson/miniconda3/envs/dask-cuda-click/lib/python3.10/site-packages/dask_cuda/cli.py", line 61, in <module>
    @cuda.command(name="worker", context_settings=dict(ignore_unknown_options=True))
AttributeError: 'function' object has no attribute 'command'
```

It looks like we indirectly depend on `click` via `dask`, so I've opened https://github.com/dask/dask/pull/10623 to propose bumping the minimum to `click>=8.1` there.

Do we also want to add that dependency here and set a similar minimum?
