### PR TITLE
Set minimum click to 8.1

### LINKED ISSUE #1271: `dask cuda` CLI doesn't work with click 8.0.x
I just ran into an issue with running `dask cuda worker` if you have `click 8.0.x`.

```console
$ conda create -n dask-cuda-click -y -c conda-forge python=3.10

$ conda activate dask-cuda-click

$ pip install dask[complete] dask-cuda==23.10.0 click==8.0.4

$ dask cuda worker
/home/jtomlinson/miniconda3/envs/dask-cuda-click/lib/python3.10/site-packages/dask/cli.py:100: UserWarning: While registering the command with name 'cuda', an exception ocurred; 'function' object has no attribute 'command'.
  warnings.warn(
Usage: dask [OPTIONS] COMMAND [ARGS]...
Try 'dask -h' for help.

Error: No such command 'cuda'.

$ python -c "import dask_cuda.cli"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jtomlinson/miniconda3/envs/dask-cuda-click/lib/python3.10/site-packages/dask_cuda/cli.py", line 61, in <module>
    @cuda.command(name="worker", context_settings=dict(ignore_unknown_options=True))
AttributeError: 'function' object has no attribute 'command'
```

It looks like we indirectly depend on `click` via `dask`, so I've opened https://github.com/dask/dask/pull/10623 to propose bumping the minimum to `click>=8.1` there.

Do we also want to add that dependency here and set a similar minimum?

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Closes #1271

### CODE REVIEW

**Comment by pentschev** [comment]
I think this shouldn't be necessary anymore if https://github.com/dask/dask/pull/10623 gets merged, right @jacobtomlinson ?

**Comment by jacobtomlinson** [comment]
That is true, but that relies on us moving our pin to whatever Dask release contains that change. If we've already pinned Dask for 23.12 I would be tempted to merge this in here still.

**Comment by quasiben** [comment]
Let's get this merged in for 23.12

**Comment by quasiben** [comment]
@jacobtomlinson can you merge with main and resolve the conflict with pyproject.toml and then we should be good

**Comment by wence-** [comment]
I fixed the merge conflict, let's see if things run

**Review by quasiben — APPROVED** [review]
