### ISSUE TITLE
AttributeError: 'ProxifyHostFile' object has no attribute 'evict'

### ISSUE THREAD

**Issue by pentschev** [rapidsai/dask-cuda#861]
After changes introduced by https://github.com/dask/distributed/pull/5543, `dask_cuda/tests/test_proxify_host_file.py::test_worker_force_spill_to_disk` is now failing:

```python
___________________________________________ test_worker_force_spill_to_disk ____________________________________________

args = (), kwargs = {}, loop = <tornado.platform.asyncio.AsyncIOLoop object at 0x7f7314ba0580>
injected_func = functools.partial(<function test_worker_force_spill_to_disk at 0x7f7314b723a0>)
cor = functools.partial(<function test_worker_force_spill_to_disk at 0x7f7314b723a0>)

    def test_func(*args, **kwargs):
        with clean() as loop:
            injected_func = functools.partial(func, *args, **kwargs)
            if iscoroutinefunction(func):
                cor = injected_func
            else:
                cor = gen.coroutine(injected_func)

>           loop.run_sync(cor, timeout=timeout)

../distributed/distributed/utils_test.py:808:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../miniconda3/envs/rn-220217/lib/python3.8/site-packages/tornado/ioloop.py:530: in run_sync
    return future_cell[0].result()
dask_cuda/tests/test_proxify_host_file.py:404: in test_worker_force_spill_to_disk
    await client.submit(f)
../distributed/distributed/client.py:287: in _result
    raise exc.with_traceback(tb)
dask_cuda/tests/test_proxify_host_file.py:399: in f
    await w.memory_monitor()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   weight = self.data.evict()
E   AttributeError: 'ProxifyHostFile' object has no attribute 'evict'

../distributed/distributed/worker.py:3752: AttributeError
```

@shwina do you have the time and will to look at this? Otherwise I'll do so.

**Comment by shwina** [comment]
Thanks, @pentschev! Happy to look into this one.
